-- MySQL Script generated by MySQL Workbench
-- Mon Jan  7 09:53:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema diginamicproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diginamicproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diginamicproject` DEFAULT CHARACTER SET utf8 ;
USE `diginamicproject` ;

-- -----------------------------------------------------
-- Table `diginamicproject`.`absencetype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diginamicproject`.`absencetype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(105) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diginamicproject`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diginamicproject`.`status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(105) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diginamicproject`.`departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diginamicproject`.`departement` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diginamicproject`.`function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diginamicproject`.`function` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diginamicproject`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diginamicproject`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `nbrDaysOfLeave` INT(11) NULL DEFAULT NULL,
  `nbrRTT` INT(11) NULL DEFAULT NULL,
  `idDepartement` INT(11) NULL DEFAULT NULL,
  `idFunction` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `idDepartement_idx` (`idDepartement` ASC),
  INDEX `idFunction_idx` (`idFunction` ASC),
  CONSTRAINT `idDepartement`
    FOREIGN KEY (`idDepartement`)
    REFERENCES `diginamicproject`.`departement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idFunction`
    FOREIGN KEY (`idFunction`)
    REFERENCES `diginamicproject`.`function` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `diginamicproject`.`absence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diginamicproject`.`absence` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `reason` VARCHAR(100) NULL DEFAULT NULL,
  `idAbsenceType` INT(11) NOT NULL,
  `idStatus` INT(11) NOT NULL,
  `idUser` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idAbsenceType_idx` (`idAbsenceType` ASC),
  INDEX `idStatus_idx` (`idStatus` ASC),
  CONSTRAINT `idAbsenceType`
    FOREIGN KEY (`idAbsenceType`)
    REFERENCES `diginamicproject`.`absencetype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idStatus`
    FOREIGN KEY (`idStatus`)
    REFERENCES `diginamicproject`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `diginamicproject`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
